# permissions for end users to view hugosites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hugosite-viewer-role
rules:
- apiGroups:
  - hugo-hoster.cedi.dev
  resources:
  - hugosites
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hugo-hoster.cedi.dev
  resources:
  - hugosites/status
  verbs:
  - get
