---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - ConfigMap
  - Service
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - Deployment
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - CronJob
  - Job
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hugo-hoster.cedi.dev
  resources:
  - HugoPages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hugo-hoster.cedi.dev
  resources:
  - HugoPages/finalizers
  verbs:
  - update
- apiGroups:
  - hugo-hoster.cedi.dev
  resources:
  - HugoPages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - hugo-hoster.cedi.dev
  resources:
  - Setting
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
